Repository upbound/platform-ref-gcp, pull requests merged in 2022-10, with the labels that each got.

#28 Only push for linux_amd64
  Makefile
Labels: size/XS

#29 Fix (misleading) comment for setting a single platform
  Makefile
Labels: size/XS

#31 Makefile: do not fail when build submodule is not checked out
  Makefile
Labels: size/XS

#32 E2E - CI improvements and wait for provider gcp before applying providerconfig
  .github/workflows/e2e.yaml
  Makefile
  test/setup.sh
Labels: size/M

#33 Further fixes for e2e workflow
  .github/workflows/e2e.yaml
  Makefile
  package/cluster/gke/composition.yaml
  test/setup.sh
Labels: size/S

#34 Update example Configuration
  examples/configuration.yaml
Labels: size/XS

#35 More waits for CI
  .github/workflows/e2e.yaml
  test/setup.sh
Labels: size/M

#36 Fix setup.sh echo command
  .github/workflows/e2e.yaml
  Makefile
  test/setup.sh
Labels: size/L
